import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import axios from "axios";
import { useEffect, useState } from "react";
import { Configuration, OpenAIApi } from "openai";
import { Button, Flex, Input } from "@chakra-ui/react";

export default function Home() {
  const [message, setMessage] = useState("");
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState<any>("");
  const [date, setDate] = useState("");

  const apiTest = async () => {
    const date = "202212";
    const result = await axios({
      method: "POST",
      url: "https://e82fpq79k3.execute-api.ap-northeast-1.amazonaws.com/default/real_estate_function",
      data: {
        date: 202212,
      },
    });
    console.log(result);
  };

  const fixData = (e: any) => {
    const { value } = e.target;
    setDate(value);
  };

  const callApi = async () => {
    const result = await axios({
      method: "POST",
    });
    console.log(date);
  };

  // const chatApi = async () => {
  //   setQuestion(message);
  //   const configuration = new Configuration({
  //     // apiKey: key,
  //     apiKey: "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",
  //   });

  //   const openai = new OpenAIApi(configuration);
  //   const result = await openai.createCompletion({
  //     model: "text-davinci-002",
  //     prompt: message,
  //     temperature: 0.7,
  //     max_tokens: 256,
  //     top_p: 1,
  //     frequency_penalty: 0,
  //     presence_penalty: 0,
  //   });

  //   console.log(result.data);
  //   setAnswer(result?.data?.choices[0]?.text);
  // };

  // const onChatMessage = (e: any) => {
  //   console.log(e.target.value);
  //   setMessage(e.target.value);
  // };

  // const submitApi = (e: any) => {
  //   setKey(e.target.value);
  // };
  useEffect(() => {
    apiTest();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.chatBox}>
          <div className={styles.chatMsgBox}>
            <div>{question}</div>
            <div className={styles.answerBox}>{answer}</div>
          </div>
          {/* <div>
            <input
              onChange={(e) => submitApi(e)}
              type="text"
              placeholder="typing api key"
            />
          </div>
          <div className={styles.chatBtnBox}>
            <input
              type="text"
              placeholder="input chat"
              className={styles.chatInputBox}
              onChange={(e) => onChatMessage(e)}
            />
            <button onClick={chatApi} className={styles.chatBtn}>
              expressHandle
            </button>
          </div> */}
          <Flex>
            <Input type={"text"} onChange={(e) => fixData(e)} />
            <Button ml={5} onClick={callApi}>
              call
            </Button>
          </Flex>
        </div>
      </main>
    </>
  );
}
